# Generated by Django 5.2.6 on 2025-09-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                ("date", models.DateField()),
                ("account_id", models.CharField(max_length=100)),
            ],
        ),
    ]
